---
# Note: This test scenario is to Test User can use Vertex AI (VAI)
#       on Custom Container Trained Custom Tabular Models from VAI-managed datasets (vmds) as Follows:
# 1) Verify that user can create a VAI-managed Tabular dataset

# ------------------------- create custom_tabular_managed_dataset datasaet---------------------------#

# --- Scenario 1 : custom_tabular_managed_dataset already exists with imported data in respective project ---#

- name: Check whether a tabular dataset named "custom_tabular_managed_dataset" exist or not through API
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: dataset_list

- name: get dataset name
  ansible.builtin.set_fact:
    dataset_name: "{{ (dataset_list.json.datasets | map (attribute='displayName')) }}"
  when: dataset_list.json | length > 0

- name: get dataset id
  ansible.builtin.set_fact:
    dataset_id: "{{ dataset_list.json.datasets | json_query(query) | map('split', '/')|map(attribute=5)|list |first }}"
  vars:
    query: "[?displayName == 'custom_tabular_managed_dataset'].name"
  when: "(dataset_name is defined) and ('custom_tabular_managed_dataset' in dataset_name)"

- name: Data is already present in dataset, no need to import it.
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets/{{ dataset_id }}/dataItems"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: load_custom_tabular_managed_response
  when: "(dataset_name is defined) and ('custom_tabular_managed_dataset' in dataset_name)"

- name: Set status flag
  ansible.builtin.set_fact: load_custom_tabular_managed_dataset_status="Passed"
  when:
    - "(dataset_name is defined) and ('custom_tabular_managed_dataset' in dataset_name)"
    - load_custom_tabular_managed_response | length > 0

- name: Log custom_tabular_managed-dataset API results
  ansible.builtin.script: >
    log.py "Vertex AI" "Create/Load custom_tabular_managed Dataset" {{ load_custom_tabular_managed_dataset_status }}
    "User can create and load custom_tabular_managed-dataset" "https://rb.gy/pupgwy"
  args:
    executable: python3
  when: "(dataset_name is defined) and ('custom_tabular_managed_dataset' in dataset_name)"

# ----- Scenario 2 : tabular Dataset does not exists in respective project, So create an tabular Dataset ---#
- name: Template entity custom_tabular_managed_dataset.json
  ansible.builtin.template:
    src: "{{ role_path }}/files/custom_tabular_managed_dataset.json.j2"
    dest: "{{ role_path }}/files/custom_tabular_managed_dataset.json"
    mode: 0644
  when: |
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('custom_tabular_managed_dataset' not in dataset_name))

- name: Create a custom_tabular_managed dataset through API
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets"
    method: POST
    body: "{{ lookup('file','custom_tabular_managed_dataset.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: load_custom_tabular_managed_response
  when: |
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('custom_tabular_managed_dataset' not in dataset_name))

- name: Set Dataset ID
  ansible.builtin.set_fact:
    dataset_id: "{{ load_custom_tabular_managed_response.json.name.split('/')[5] }}"
  when: |
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('custom_tabular_managed_dataset' not in dataset_name))

- name: Set status flag
  ansible.builtin.set_fact: load_custom_tabular_managed_dataset_status="Passed"
  when:
    - "(dataset_name is not defined) or ((dataset_name is defined) and ('custom_tabular_managed_dataset' not in dataset_name))"
    - load_custom_tabular_managed_response.status == 200

- name: Log custom_tabular_managed-dataset API results
  ansible.builtin.script: >
    log.py "Vertex AI" "Create/Load custom_tabular_managed Dataset" {{ load_custom_tabular_managed_dataset_status }}
    "User can create and load custom_tabular_managed-dataset" "https://rb.gy/pupgwy"
  args:
    executable: python3
  when: |
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('custom_tabular_managed_dataset' not in dataset_name))
