---
# Note: This test scenario is to Test User can use Vertex AI (VAI)
# on Custom-Container Trained Image Models from VAI-un-managed datasets as Follows:

# --------------------------------------- creating an Endpoint--------------------------------#
# Verify that user can create an endpoint via Vertex AI

# -------- Scenario 1 : custom_image_unmanaged endpoint already exists in respective project ---------#
- name: Get the List of existing endpoints.
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/endpoints"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: endpoint_list

- name: get the list of existing endpoints names
  ansible.builtin.set_fact:
    endpoint_name_list: "{{ (endpoint_list.json.endpoints | map (attribute='displayName')) }}"
  when: "endpoint_list.json is defined"

- name: get endpoint id of existing endpoint
  ansible.builtin.set_fact:
    endpoint_id: |
      {{ endpoint_list.json.endpoints | json_query(query) | map('split', '/')|
      map(attribute=5)|list |first }}
  vars:
    query: "[?displayName == 'custom_image_unmanaged_endpoint'].name"
  when:
    - endpoint_name_list is defined
    - "'custom_image_unmanaged_endpoint' in endpoint_name_list"

- name: Set status flag
  ansible.builtin.set_fact: create_custom_image_unmanaged_endpoint_status="Passed"
  when:
    - endpoint_name_list is defined
    - "'custom_image_unmanaged_endpoint' in endpoint_name_list"

- name: Log create custom_image_unmanaged-endpoint results
  ansible.builtin.script: >
    log.py "Vertex AI" "create custom_image_unmanaged endpoint" {{ create_custom_image_unmanaged_endpoint_status }}
    "User can create a custom_image_unmanaged endpoint" "https://rb.gy/y17xdd"
  args:
    executable: python3
  when:
    - endpoint_name_list is defined
    - "'custom_image_unmanaged_endpoint' in endpoint_name_list"

# -------Scenario 2 : custom_image_unmanaged endpoint does not exists in respective project---------#
- name: create an endpoint
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/endpoints"
    method: POST
    body: "{{ lookup('file','custom_image_unmanaged_endpoint.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: create_custom_image_unmanaged_endpoint_response
  when: "(endpoint_name_list is not defined) or ('custom_image_unmanaged_endpoint' not in endpoint_name_list)"

- name: set endpoint ID
  ansible.builtin.set_fact:
    endpoint_id: "{{ create_custom_image_unmanaged_endpoint_response.json.name.split('/')[5] }}"
  when: "(endpoint_name_list is not defined) or ('custom_image_unmanaged_endpoint' not in endpoint_name_list)"

- name: Pause for 10 seconds
  when: "(endpoint_name_list is not defined) or ('custom_image_unmanaged_endpoint' not in endpoint_name_list)"
  ansible.builtin.pause:
    seconds: 10

- name: Set status flag
  ansible.builtin.set_fact: create_custom_image_unmanaged_endpoint_status="Passed"
  when:
    - "(endpoint_name_list is not defined) or ('custom_image_unmanaged_endpoint' not in endpoint_name_list)"
    - create_custom_image_unmanaged_endpoint_response.status == 200

- name: Log create custom_image_unmanaged-endpoint results
  ansible.builtin.script: >
    log.py "Vertex AI" "create custom_image_unmanaged endpoint" {{ create_custom_image_unmanaged_endpoint_status }}
    "User can create a custom_image_unmanaged endpoint" "https://rb.gy/y17xdd"
  args:
    executable: python3
  when: "(endpoint_name_list is not defined) or ('custom_image_unmanaged_endpoint' not in endpoint_name_list)"
