---
# Note: This test scenario is to Test User can use Vertex AI (VAI)
#       on Custom Container Trained Custom Tabular Models from VAI-managed datasets (vmds) as Follows:
#       1) Verify that user can deploy the trained Custom Tabular model to a Vertex AI endpoint

# --------------------------------------- deploy model to an endpoint--------------------------------#

# Verify that user can deploy an custom_tabular_managed model to an endpoint via Vertex AI

# --------- Scenario 1 : custom_tabular_managed model already deployed to respective endpoint --------#

- name: get list of already deployed models to an "custom_tabular_managed_endpoint" endpoint
  ansible.builtin.command: |
    gcloud ai endpoints describe {{ endpoint_id }} --project={{ project }} --region={{ vertex_region }}
    --flatten=deployedModels[] --format=csv(deployedModels.displayName)
  register: deploy_custom_tabular_managed_model_response
  when:
     - endpoint_name_list is defined
     - "'custom_tabular_managed_endpoint' in endpoint_name_list"

# ----- Scenario 2 : custom_tabular_managed model has not been deployed to respective endpoint,
#                    thus deploying the custom_tabular_managed model ------------#

- name: deploy the model to an endpoint
  ansible.builtin.command: |
    gcloud ai endpoints deploy-model {{ endpoint_id }} --region={{ vertex_region }} --model={{ model_id }}
    --display-name=deploy_custom_tabular_managed_model --machine-type=n1-standard-2 --min-replica-count=1
    --max-replica-count=1 --traffic-split=0=100
  register: newly_deploy_custom_tabular_managed_model_response
  when: |
    (deploy_custom_tabular_managed_model_response.stdout is not defined) or
    ((deploy_custom_tabular_managed_model_response.stdout is defined) and
    ('deploy_custom_tabular_managed_model' not in deploy_custom_tabular_managed_model_response.stdout))
