---
#  Note: This test scenario is to Test User can use Vertex AI (VAI) on
#        Custom-Container Trained Image Models from VAI-un-managed datasets as Follows:
#  1) Verify that user can deploy a VAI-Imported Custom Image model to an endpoint on Vertex AI

# --------------------------------------- deploy model to an endpoint--------------------------------#

# Verify that user can deploy an custom_image_unmanaged model to an endpoint via Vertex AI

# ----- Scenario 1 : custom_image_unmanaged model already deployed to respective endpoint -------#

- name: get list of already deployed models to an "custom_image_unmanaged_endpoint" endpoint
  ansible.builtin.command: >
    gcloud ai endpoints describe {{ endpoint_id }} --project={{ project }} --region={{ vertex_region }}
    --flatten=deployedModels[] --format=csv(deployedModels.displayName)
  register: deploy_custom_image_unmanaged_model_response
  when:
     - endpoint_name_list is defined
     - "'custom_image_unmanaged_endpoint' in endpoint_name_list"

# ---- Scenario 2 : custom_image_unmanaged model has not been deployed to respective endpoint,
# ----------------- thus deploying the custom_image_unmanaged model

- name: deploy the model to an endpoint
  ansible.builtin.command: >
    gcloud ai endpoints deploy-model {{ endpoint_id }} --region={{ vertex_region }} --model={{ model_id }}
    --display-name=deploy_custom_image_unmanaged_model --machine-type=n1-standard-2 --min-replica-count=1
    --max-replica-count=1 --traffic-split=0=100
  register: newly_deploy_custom_image_unmanaged_model_response
  when: >
    (deploy_custom_image_unmanaged_model_response.stdout is not defined) or
    ((deploy_custom_image_unmanaged_model_response.stdout is defined) and
    ('deploy_custom_image_unmanaged_model' not in deploy_custom_image_unmanaged_model_response.stdout))
