---

# Verify that user can evaluate an AutoML-image model via Vertex AI

- name: Evaluate image model
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/models/{{ model_id }}/evaluations"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: evaluate_model_image_response

- name: Set status flag
  ansible.builtin.set_fact: evaluate_image_model_status="Passed"
  when: evaluate_model_image_response.status == 200

- name: Log evaluate image-model results
  ansible.builtin.script: >
    log.py "Vertex AI" "Evaluate Image Model" {{ evaluate_image_model_status }}
    "User can Evaluate image-Model" "https://rb.gy/itdynw"
  args:
    executable: python3
