---

# Note: This test scenario is to Test User can use Vertex AI (VAI)
#       on VAI-Prebuilt Container Trained Custom Image Models from VAI-un-managed datasets as Follows:
# 1) Verify that user can make a prediction from a deployed Customer Image model via Vertex AI

# -------------------- online prediction using deployed model-----------------#

# Verify that user can make an online prediction from a deployed prebuilt_image_unmanaged model via Vertex AI

- name: Execute ansible.builtin.command to perform online prediction using prebuilt_image_unmanaged model
  ansible.builtin.command: >
    gcloud ai endpoints predict {{ endpoint_id }} --region={{ vertex_region }}
    --json-request={{ role_path }}/files/prebuilt_image_unmanaged_model_prediction.json
  register: predict_model_response
  changed_when: false

- name: prediction information
  ansible.builtin.debug:
    msg:
      - "{{ lookup('file', 'model_image_labels.txt') }}"
      - "{{ predict_model_response.stdout }}"

- name: Set status flag
  ansible.builtin.set_fact: predict_prebuilt_image_unmanaged_model_status="Passed"
  when: predict_model_response.stdout | length > 0

- name: Log predict using prebuilt_image_unmanaged-model results
  ansible.builtin.script: >
    log.py "Vertex AI" "predict using prebuilt_image_unmanaged model"
    {{ predict_prebuilt_image_unmanaged_model_status }}
    "User can do prediction using prebuilt_image_unmanaged model" "https://rb.gy/gutqgp"
  args:
    executable: python3
  when: predict_model_response.stdout | length > 0

- name: Cleanup duplicate files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ role_path }}/files/prebuilt_image_unmanaged_train.json"
