---
#   Verify that user can create and load a tabular dataset via Vertex AI

# --------- Scenario 1 : tabular Dataset already exists with imported data in respective project ----------#

- name: Check whether a tabular dataset named "test_new_tabular_dataset" exist or not through API
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: dataset_list

- name: get dataset name
  ansible.builtin.set_fact:
    dataset_name: "{{ (dataset_list.json.datasets | map (attribute='displayName')) }}"
  when: dataset_list.json | length > 0

- name: get dataset id
  ansible.builtin.set_fact:
    dataset_id: "{{ dataset_list.json.datasets | json_query(query) | map('split', '/')|map(attribute=5)|list |first }}"
  vars:
    query: "[?displayName == 'test_new_tabular_dataset'].name"
  when: "(dataset_name is defined) and ('test_new_tabular_dataset' in dataset_name)"

- name: Data is already present in dataset, no need to import it.
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets/{{ dataset_id }}/dataItems"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: load_tabular_response
  when: "(dataset_name is defined) and ('test_new_tabular_dataset' in dataset_name)"

- name: Set status flag
  ansible.builtin.set_fact: load_tabular_dataset_status="Passed"
  when:
    - "(dataset_name is defined) and ('test_new_tabular_dataset' in dataset_name)"
    - load_tabular_response | length > 0

- name: Log tabular-dataset API results
  ansible.builtin.script: >
    log.py "Vertex AI" "Create/Load tabular Dataset" {{ load_tabular_dataset_status }}
    "User can create and load tabular-dataset" "https://rb.gy/gwfril"
  args:
    executable: python3
  when: "(dataset_name is defined) and ('test_new_tabular_dataset' in dataset_name)"

# --- Scenario 2 : tabular Dataset does not exists in respective project, So create an tabular Dataset ----#

- name: upload wdbcd.csv to GCS bucket
  ansible.builtin.command: >
    gsutil cp {{ role_path }}/files/wdbcd.csv {{ shared_bucket }}vai_testing/tables/wdbcd.csv
  when: >
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))

- name: Template entity tabular_request.json
  ansible.builtin.template:
    src: "{{ role_path }}/files/tabular_request.json.j2"
    dest: "{{ role_path }}/files/tabular_request.json"
    mode: 0644
  when: >
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))

- name: Create a tabular dataset through API
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/datasets"
    method: POST
    body: "{{ lookup('file','tabular_request.json') }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: load_tabular_response
  when: >
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))

- name: Set Dataset ID
  ansible.builtin.set_fact:
    dataset_id: "{{ load_tabular_response.json.name.split('/')[5] }}"
  when: >
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))

- name: Set status flag
  ansible.builtin.set_fact: load_tabular_dataset_status="Passed"
  when:
    - "(dataset_name is not defined) or ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))"
    - load_tabular_response.status == 200

- name: Log tabular-dataset API results
  ansible.builtin.script: >
    log.py "Vertex AI" "Create/Load Tablular Dataset" {{ load_tabular_dataset_status }}
    "User can create and load tabular-dataset" "https://rb.gy/gwfril"
  args:
    executable: python3
  when: >
    (dataset_name is not defined) or
    ((dataset_name is defined) and ('test_new_tabular_dataset' not in dataset_name))
