---

# Verify that user can make an online prediction from a deployed AutoML-text model via Vertex AI

- name: Execute ansible.builtin.command to perform online prediction using text Automl model
  ansible.builtin.command: >
    gcloud ai endpoints predict {{ endpoint_id }} --region={{ vertex_region }}
    --json-request={{ role_path }}/files/text_model_prediction.json
  register: predict_model_response
  changed_when: false

- name: prediction information
  ansible.builtin.debug:
    msg: "{{ predict_model_response.stdout }}"

- name: Set status flag
  ansible.builtin.set_fact: predict_text_model_status="Passed"
  when: predict_model_response.stdout | length > 0

- name: Log predict text-model results
  ansible.builtin.script: >
    log.py "Vertex AI" "predict using text model" {{ predict_text_model_status }}
    "User can do prediction using text model" "https://rb.gy/sraqdy"
  args:
    executable: python3
  when: predict_model_response.stdout | length > 0

- name: Cleanup duplicate files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ role_path }}/files/text_dataset_import.json"
    - "{{ role_path }}/files/text_train.json"
