---

# Verify that user can evaluate an AutoML-text model via Vertex AI
- name: Evaluate text model
  ansible.builtin.uri:
    url: "https://{{ vertex_region }}-aiplatform.googleapis.com/v1/projects/{{ project }}/\
         locations/{{ vertex_region }}/models/{{ model_id }}/evaluations"
    method: GET
    headers:
      Content-Type: "application/json"
      Authorization: Bearer "{{ gcloud_auth }}"
  register: evaluate_model_text_response

- name: Set status flag
  ansible.builtin.set_fact: evaluate_text_model_status="Passed"
  when: evaluate_model_text_response.status == 200

- name: Log evaluate text-model results
  ansible.builtin.script: >
    log.py "Vertex AI" "Evaluate text Model" {{ evaluate_text_model_status }}
    "User can Evaluate text-Model" "https://rb.gy/6wpcvd"
  args:
    executable: python3
